name: Assign User

on:
  pull_request:
    types: [ labeled ]
  workflow_dispatch:

jobs:
  add_assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.github_token }}
          assignees: ${{ github.actor }}
